services:
    zikula_scribite_module.editor.ckeditor:
        class: Zikula\ScribiteModule\Editor\CKEditor\CKEditor
        arguments:
          - '@translator.default'
          - '@zikula_extensions_module.api.variable'
          - '@event_dispatcher'
        tags:
          - { name: scribite.editor, id: CKEditor }

    zikula_scribite_module.editor.mark_it_up_editor:
        class: Zikula\ScribiteModule\Editor\MarkItUp\MarkItUpEditor
        arguments:
          - '@translator.default'
          - '@zikula_extensions_module.api.variable'
        tags:
            - { name: scribite.editor, id: MarkItUp }

    zikula_scribite_module.editor.tiny_mce_editor:
        class: Zikula\ScribiteModule\Editor\TinyMce\TinyMceEditor
        arguments:
          - '@translator.default'
          - '@zikula_extensions_module.api.variable'
          - '@event_dispatcher'
        tags:
            - { name: scribite.editor, id: TinyMce }
